version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://api.muforbelmond.tech/api
    container_name: portfolio-admin
    restart: always
    ports:
      - "3081:3081"

